<a href="https://colab.research.google.com/github/luudangnguyenha04012003/ThucHanhToanCaoCap/blob/main/B%C3%A0i_t%E1%BA%ADp_ch%C6%B0%C6%A1ng_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Thực hành 1

In [12]:
x=3
print(x)

3


In [13]:
import math
x = math.sqrt(1+x)
print(x)

2.0


In [14]:
x = math.sqrt(1+x)
print(x)

1.7320508075688772


In [15]:
x = math.sqrt(1+x)
print(x)

1.6528916502810695


In [17]:
x = math.sqrt(x)
print(x)

1.2856483384973783


Thực hành 2

In [19]:
import math
x=3
lap=1
while (x != math.sqrt(x+1)): 
  x = math.sqrt(x+1) 
  lap = lap  +1    

In [20]:
x

1.618033988749895

In [21]:
lap

32

Thực hành 3

In [22]:
import sympy as sp  
from sympy import Symbol  
x = Symbol('x') 
sp.solve(x-sp.sqrt(1+x),x) 

[1/2 + sqrt(5)/2]

Thực hành 4

In [23]:
import numpy as np 
v1 = np.array([1., 2., 3.])  
v2 = np.array([2., 1., 0.]) 
v3 = v1 + v2    
v3

array([3., 3., 3.])

Thực hiện phép toàn trên vector

In [24]:
3*v1  + 2*v2 

array([7., 8., 9.])

In [25]:
[1, 2, 3] + [2, 1, 0] 

[1, 2, 3, 2, 1, 0]

In [26]:
3*[1, 2, 3] + 2*[2, 1, 0] 

[1, 2, 3, 1, 2, 3, 1, 2, 3, 2, 1, 0, 2, 1, 0]

Ghép nối 2 hoặc nhiều vector

In [29]:
v4 = np.hstack([v1, v2]) 
v4

array([1., 2., 3., 2., 1., 0.])

Phép nhân vô hướng 2 vector

In [30]:
np.dot(v1, v2)

4.0

Tính toán giá trị sin của vector

In [31]:
angles = np.linspace(0, np.pi/2, 5) 
angles 

array([0.        , 0.39269908, 0.78539816, 1.17809725, 1.57079633])

In [34]:
 np.sin(angles)

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

Thực hành 5